### ISSUE TITLE
How to add image in view pager can u give me a example

### ISSUE THREAD

**Issue by mahesh825mahi** [kassisdion/ViewPagerWithIndicator#3]

**Comment by kassisdion** [comment]
As stated in the README, you can take a look at the sample application (located in app/*).
In  [MainActivity.java](https://github.com/kassisdion/ViewPagerWithIndicator/blob/master/app/src/main/java/com/kassisdion/viewpagerwithindicator/demo/MainActivity.java) , you'll see a sample with textview and it's really easy to convert the code to make it work with imageView
